name: Configuration du projet
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest

      - name: Recuperation du projet
        uses: actions/checkout@v4
      
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Installation des dependences
        run: npm ci

      - name: build message
        run: echo "Build de l'application..."
